services:
  - type: web
    name: fastapi
    runtime: docker
    plan: free
    repo: mongodb+srv://madinaamankeldinova:madina78010506@madina.bwesxut.mongodb.net/?retryWrites=true&w=majority
    region: frankfurt
    branch: main
    envVars:
      - key: MONGO_URL
        sync: false
    buildFilter:
      paths:
      - app/**
